name: Build Docker Image
on:
  workflow_call:
    inputs:
      DOCKERFILE:
        type: string
        default: Dockerfile
      ENV_TAG:
        type: string
        default: latest
      ORGANIZATION_NAME:
        type: string
        default: ucode-io
      TAG:
        type: string
        default: ${{ github.run_number }}
        # required: true
    secrets:
      REGISTRY:
        required: false
      REGISTRY_USER:
        required: false
      REGISTRY_PASSWORD:
        required: false


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY_USER: ${{ secrets.REGISTRY_USER || github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD || secrets.GITHUB_TOKEN }}
      REGISTRY: ${{ secrets.REGISTRY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Try to download .env artifact
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: env-file
          path: .

      - name: Check if .env file exists
        run: |
          if [ -f .env ]; then
            echo ".env file found, including it in build context."
          else
            echo "No .env file found, skipping."
          fi

      - name: Log in to Docker registry
        run: |
          echo "${{ env.REGISTRY_PASSWORD }}" | docker login "${{ env.REGISTRY }}" --username "${{ env.REGISTRY_USER }}" --password-stdin

      - name: Build Docker image
        run: |
          make build-image \
            DOCKERFILE=${{ inputs.DOCKERFILE }} \
            TAG=${{ inputs.TAG }} \
            PROJECT_NAME=${{ inputs.ORGANIZATION_NAME }} \
            REGISTRY=${{ secrets.REGISTRY }} \
            ENV_TAG=${{ inputs.ENV_TAG }}

      - name: Push Docker image
        run: |
          make push-image \
            TAG=${{ inputs.TAG }} \
            PROJECT_NAME=${{ inputs.ORGANIZATION_NAME }} \
            REGISTRY=${{ secrets.REGISTRY }} \
            ENV_TAG=${{ inputs.ENV_TAG }}

      - name: Clear local images
        run: |
          make clear-image \
            TAG=${{ inputs.TAG }} \
            PROJECT_NAME=${{ inputs.ORGANIZATION_NAME }} \
            REGISTRY=${{ secrets.REGISTRY }} \
            ENV_TAG=${{ inputs.ENV_TAG }}

      - name: Clear .env artifact
        uses: geekyeggo/delete-artifact@v5
        continue-on-error: true
        with:
            name: env-file
